spring.application.name=sendly
spring.datasource.url=jdbc:mysql://@yamabiko.proxy.rlwy.net:37416/railway
spring.datasource.username=root
spring.datasource.password=lGCZVMuQwXulGzlgNbzCWKbJttSPKcwL
server.port=${PORT:8080}