spring.application.name=ProjetoGenesisAPI
spring.datasource.url=jdbc:oracle:thin:@//10.110.167.146:1521/cbrms_4pw_gru.subnetexadatali.vcnexadataocisp.oraclevcn.com
spring.datasource.username=joao
spring.datasource.password=080514