spring.application.name=painel_BD
spring.datasource.url=jdbc:oracle:thin:@//10.110.167.146:1521/cbrms_4pw_gru.subnetexadatali.vcnexadataocisp.oraclevcn.com
spring.datasource.username=joao
spring.datasource.password=080514

server.port=6842
server.address=0.0.0.0

spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.serialization.write-dates-as-timestamps=false

#Coruja
#spring.datasource.url=jdbc:oracle:thin:@//10.110.167.188:1521/cbrms_4pw_gru.subnetexadatali.vcnexadataocisp.oraclevcn.com
#spring.datasource.username=joao
#spring.datasource.password=080514


#ServidorTeste
#spring.application.name=painel_BD
#spring.datasource.url=jdbc:oracle:thin:@//10.120.100.215:1521/pdbrms.subnetcobasihmg.vcncobasiautosk.oraclevcn.com
#spring.datasource.username=matheus
#spring.datasource.password=51872763871