spring.application.name=painel_BD
spring.datasource.url=jdbc:oracle:thin:@//10.110.167.188:1521/cbrms_4pw_gru.subnetexadatali.vcnexadataocisp.oraclevcn.com
spring.datasource.username=joao
spring.datasource.password=080514


server.port:1845