spring.application.name=registerManager
spring.datasource.url=jdbc:oracle:thin:@//10.110.167.146:1521/cbzant_qdg_gru.subnetexadatali.vcnexadataocisp.oraclevcn.com
spring.datasource.username=zeusretail
spring.datasource.password=cob753097asi
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.devtools.restart.enabled=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
spring.servlet.multipart.enabled=true
spring.websocket.enabled=true
server.port= 9091
